stages:
  - build
  - deploy
  - notify

variables:
  ENV_FILE: /home/admin/universe/uni-conf/.env
  BUILD_DIR: 'dist/apps/front'

check:
  except:
    - master
  tags: [front]
  stage: build
  script:
    - npm ci
    - npm run after-commit

build:
  only:
    - master
  tags: [front]
  stage: build
  script:
    - npm ci
    - npm run after-commit
    - cp $ENV_FILE ./apps/front
    - nx build front
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 20 minutes

deploy:
  only:
    - master
  tags: [front]
  stage: deploy
  script:
    - netlify deploy --dir=$BUILD_DIR --prod
    - sh ci-notify.sh ✅

notify_error:
  stage: notify
  tags: [front]
  script:
    - sh ci-notify.sh ❌
  when: on_failure
