stages:
  - build
  - deploy

variables:
  BUILD_DIR: "build"

build:
  tags: [front]
  stage: build
  script:
    - npm i
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 20 minutes

deploy:
  only:
    - master
  tags: [front]
  stage: deploy
  script:
    - netlify deploy --dir=$BUILD_DIR --prod
