stages:
  - build
  - deploy
  - notify

variables:
  BUILD_DIR: 'dist'

check:
  except:
    - master
  tags: [front]
  stage: build
  script:
    - npm ci
    - npm run check

build:
  only:
    refs:
      - master
  tags: [front]
  stage: build
  script:
    - npm ci
    - npm run check
    - npm run build
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 20 minutes

# deploy:
#   only:
#     refs:
#       - master
#   tags: [front]
#   stage: deploy
#   script:
#     - netlify deploy --dir=$BUILD_DIR --prod
#     - sh ci-notify.sh ✅

notify_error:
  stage: notify
  tags: [front]
  script:
    - sh ci-notify.sh ❌
  when: on_failure
