export const APP = '/'
export const FINISH_REGISTRATION = APP + 'finish-registration'
export const STUDY = APP + 'study'
export const TEACH = APP + 'teach'
export const TUNE = APP + 'settings'
export const STATS = APP + 'stats'
export const STUDY_ID = STUDY + '/:id'
export const ANY = '*'
